### ISSUE TITLE
The first tag button should only allow one tagged piece of text to be collected

### ISSUE THREAD

**Issue by axgreen** [zooniverse/wellcome#34] opened 2015-11-10 13:51 UTC
This is so that we can be sure the other tags in an issue relate to the first piece of text. Otherwise it's possible, and tempting, to combine several separate issues within one tag set.

**Comment by eatyourgreens** [comment] 2015-11-10 13:55
Duplicate of #23

**Closed by eatyourgreens** 2015-11-10 13:55 UTC
